import { ContentCardProps, ContentObjProps } from '@/types/content';

export const pinList: ContentObjProps[] = [
  {
    contentId: 0,
    lat: '35.1718307905573',
    lng: '129.055662132633',
    nickname: '냥이장',
    name: '키키',
    catPersonalities: [
      'LIKES_PEOPLE',
      'GETS_ALONG_WITH_CATS',
      'LOVES_TO_CUDDLE',
    ],
    neuter: 'YES',
    group: 'YES',
    description:
      '지난달 공원에 길고양이 겨울집이 설치된 이후로 따뜻하게 지내고 있어요. 사람도 좋아하고 애교가 많아서 공원의 마스코트입니다!!',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
    jibunAddrName: '',
    jibunMainAddrNo: '',
    jibunSido: '',
    jibunSigungu: '',
    jibunDong: '',
    jibunSubAddrNo: '',
    comment: 24,
    follow: 106,
    catEmoji: 3,
    images: [],
    numberOfCatSlaves: 1,
    numberOfComments: 2,
    countOfBookMark: 3,
    userUid: 4,
    bookMark: false,
  },
  {
    contentId: 1,
    lat: '35.1718307905573',
    lng: '129.055662132633',
    nickname: '냥이장',
    name: '키키',
    catPersonalities: [
      'LIKES_PEOPLE',
      'GETS_ALONG_WITH_CATS',
      'LOVES_TO_CUDDLE',
    ],
    neuter: 'YES',
    group: 'YES',
    description:
      '지난달 공원에 길고양이 겨울집이 설치된 이후로 따뜻하게 지내고 있어요. 사람도 좋아하고 애교가 많아서 공원의 마스코트입니다!!',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
    jibunAddrName: '',
    jibunMainAddrNo: '',
    jibunSido: '',
    jibunSigungu: '',
    jibunDong: '',
    jibunSubAddrNo: '',
    comment: 24,
    follow: 106,
    catEmoji: 3,
    images: [],
    numberOfCatSlaves: 1,
    numberOfComments: 2,
    countOfBookMark: 3,
    userUid: 4,
    bookMark: false,
  },
  {
    contentId: 2,
    lat: '35.1718307905573',
    lng: '129.055662132633',
    nickname: '냥이장',
    name: '키키',
    catPersonalities: [
      'LIKES_PEOPLE',
      'GETS_ALONG_WITH_CATS',
      'LOVES_TO_CUDDLE',
    ],
    neuter: 'YES',
    group: 'YES',
    description:
      '지난달 공원에 길고양이 겨울집이 설치된 이후로 따뜻하게 지내고 있어요. 사람도 좋아하고 애교가 많아서 공원의 마스코트입니다!!',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
    jibunAddrName: '',
    jibunMainAddrNo: '',
    jibunSido: '',
    jibunSigungu: '',
    jibunDong: '',
    jibunSubAddrNo: '',
    comment: 24,
    follow: 106,
    catEmoji: 3,
    images: [],
    numberOfCatSlaves: 1,
    numberOfComments: 2,
    countOfBookMark: 3,
    userUid: 4,
    bookMark: false,
  },
  {
    contentId: 3,
    lat: '35.1718307905573',
    lng: '129.055662132633',
    nickname: '냥이장',
    name: '키키',
    catPersonalities: [
      'LIKES_PEOPLE',
      'GETS_ALONG_WITH_CATS',
      'LOVES_TO_CUDDLE',
    ],
    neuter: 'YES',
    group: 'YES',
    description:
      '지난달 공원에 길고양이 겨울집이 설치된 이후로 따뜻하게 지내고 있어요. 사람도 좋아하고 애교가 많아서 공원의 마스코트입니다!!',
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
    jibunAddrName: '',
    jibunMainAddrNo: '',
    jibunSido: '',
    jibunSigungu: '',
    jibunDong: '',
    jibunSubAddrNo: '',
    comment: 24,
    follow: 106,
    catEmoji: 3,
    images: [],
    numberOfCatSlaves: 1,
    numberOfComments: 2,
    countOfBookMark: 3,
    userUid: 4,
    bookMark: false,
  },
];

export const comments = [
  {
    contentId: 0,
    nickname: '방구집사수아임당',
    comment:
      '드뎌 저도 봤어요...!!! 더미더미더미 텍스트 더미가 더미를 했는데 와 진짜 더미해요ㅠㅠ 참고로 간식을 진짜 잘 먹더라구요. 편의점에서 츄르 하나씩 사서 가세용..ㅎㅎ',
    likes: 26,
    isLike: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    contentId: 1,
    nickname: '백엔드가짱입니다',
    comment: `거창에도 귀여운 냥이는 존재한다. 진짜 짱 귀엽다.
      세상 모든 사람들이 우리 동네 길냥이들을 알았으면 좋겠다.`,
    likes: 1123,
    isLike: false,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
  {
    contentId: 2,
    nickname: '고양이알러지짜증나ㅠ',
    comment:
      '드뎌 저도 봤어요...!!! 더미더미더미 텍스트 더미가 더미를 했는데 와 진짜 더미해요ㅠㅠ 참고로 간식을 진짜 잘 먹더라구요. 편의점에서 츄르 하나씩 사서 가세용..ㅎㅎ',
    likes: 124124,
    isLike: true,
    createdAt: '2024-01-18',
    updatedAt: '2024-01-18',
  },
];
