import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import RootWrapper from '@/components/RootWrapper';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${inter.className} bg-gray-100`}>
        <RootWrapper>
          <header className='h-10'></header>
          <div className='px-5'>{children}</div>
          <footer className='w-full h-20 bg-gray-200 absolute bottom-0 left-0'></footer>
        </RootWrapper>
      </body>
    </html>
  );
}
