name: FE CI/CD Workflow

on:
  push:
    branches:
      - dev
      - main

jobs:
  change-build-name:
    runs-on: ubuntu-latest
    outputs:
      build_name: ${{ steps.set_name.outputs.build_name }}
    steps:
      - name: Set Build Name
        id: set_name
        run: echo "::set-output name=build_name::#${{ github.run_number }} | FE | branch = ${{ github.ref_name }}"

  set-env-vars:
    runs-on: ubuntu-latest
    needs: change-build-name
    outputs:
      docker-image: ${{ steps.set-envs.outputs.docker-image }}
      ecr-repository: ${{ steps.set-envs.outputs.ecr-repository }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Set Development Environment Variables
        id: set-envs
        if: github.ref_name == 'dev'
        run: |
          ECR_REPOSITORY=$(aws ssm get-parameter --name /dev/front/ecr --query 'Parameter.Value' --output text)
          DOCKER_IMAGE=$(aws ssm get-parameter --name /dev/front/image-name --query 'Parameter.Value' --output text)

          echo "ecr-repository=$ECR_REPOSITORY" >> "$GITHUB_OUTPUT"
          echo "docker-image=$DOCKER_IMAGE" >> "$GITHUB_OUTPUT"

          echo "ecr-repository=$ECR_REPOSITORY"
          echo "docker-image=$DOCKER_IMAGE"

  docker-build:
    runs-on: ubuntu-latest
    needs: set-env-vars
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        env: 
          ECR_REPOSITORY: ${{ needs.set-env-vars.outputs.ecr-repository }}
          DOCKER_IMAGE: ${{ needs.set-env-vars.outputs.docker-image }}
        run: |
          docker buildx build -f ./dockerfiles/dev.Dockerfile -t $ECR_REPOSITORY/$DOCKER_IMAGE .
          
          # Docker 이미지 ID를 GitHub 환경 변수로 설정

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref_name == 'dev'
    steps:
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ steps.set-env-vars.outputs.ecr-repository }}

      - name: Push Docker Image to ECR
        run: |
          docker tag $DOCKER_IMAGE:$GITHUB_RUN_NUMBER $ECR_REPOSITORY:$GITHUB_RUN_NUMBER
          docker tag $DOCKER_IMAGE:latest $ECR_REPOSITORY:latest
          docker push $ECR_REPOSITORY:$GITHUB_RUN_NUMBER
          docker push $ECR_REPOSITORY:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-push
    if: github.ref_name == 'dev'
    steps:
      - name: Deploy to Dev Environment
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ env.TARGET_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $ECR_REPOSITORY
            docker compose pull && docker compose up -d
